### ISSUE TITLE
Event as function instead of string

### ISSUE THREAD

**Issue by thipages** [Gurigraphics/DOMinus.js#20]
Hi,
Could be interesting to move
from `HTML.element={html='text', onclick:"update()"};`
to `HTML.element={html='text', onclick: ()=> update() };`

A quick and dirty implementation could  be to identify the two first character property starting with `on`

**Comment by Gurigraphics** [comment]
Why would it be better than that?
```
<button onclick="update()">Click me</button>
```

**Comment by thipages** [comment]
From a result point of view , nothing.
The point is more for development

**Comment by Gurigraphics** [comment]
I think that is only more code. 
onclick: ()=> update()
onkeypress: ()=> update()
onmouseover: ()=> update()
etc

**Comment by thipages** [comment]
Two advantages
1. Replace hard coding string => good for IDEs and code check
2. It allows to do in one line (a bit like style vs class) : 
```javascript
HTML.element={html='text', onclick: ()=> {/* doSomething */ };
```

**Comment by Gurigraphics** [comment]
But this code is not mounting the HTML:
```
HTML.element={ 
  html='text', 
  onclick: ()=> {/* doSomething()*/ }
};
<button onclick="HTML.element.onclick()">Click me</button>
```

I prefer to keep this in separate module.
```
HTML.element={ 
  html='text', 
  onclick: "EVENT.element.click()"
};
<button onclick="EVENT.element.update()">Click me</button>
EVENT.element.click= function(){

}
```
Others prefer use "addEventListener".
Mix events with HTML is like Vue.

**Comment by thipages** [comment]
For completion, Function may be converted to Json and then evaluated
[https://stackoverflow.com/questions/12651977/why-cant-you-stringify-a-function-expression](https://stackoverflow.com/questions/12651977/why-cant-you-stringify-a-function-expression)
[https://github.com/vkiryukhin/jsonfn/blob/master/jsonfn.js](https://github.com/vkiryukhin/jsonfn/blob/master/jsonfn.js)
